---
name: Brancen
surname: Gregory
position: "Versatile Data Professional with Multidisciplinary Expertise"
address: "3317 S Toledo Place, Tulsa, Oklahoma 74135"
phone: (918) 497-7776
email: "brancengregory@gmail.com"
github: brancengregory
linkedin: brancengregory
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::moderncv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tibble)
library(dplyr)
```

# Career Experience

```{r}
tribble(
  ~ Position, ~ Year, ~ Organization, ~ Where,
  "Research Director", "2022", "Oklahoma Policy Institute", "Tulsa, OK",
  "Senior Data Analyst", "2021", "Oklahoma Policy Institute", "Tulsa, OK",
  "Data Analyst", "2021", "Oklahoma Policy Institute", "Tulsa, OK",
  "Clinical Data Analyst", "2018", "Muskogee (Creek) Nation Department of Health", "Okmulgee, OK",
  "SBIRT Data Analyst", "2018", "Muskogee (Creek) Nation Department of Health", "Sapulpa, OK"
) |>
  detailed_entries(Position, Year, Organization, Where)
```

# Education

```{r}
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Bachelor of Science, Economics major, Philosophy and Religious Studies minors", "2017", "University of Tulsa", "Tulsa, OK",
) |>
  detailed_entries(Degree, Year, Institution, Where)
```

# Publications

```{r}
knitr::write_bib(c("ojodb", "ojoutils"), "packages.bib")

bibliography_entries("packages.bib") %>%
  arrange(desc(author$family), issued)
```

# References

```{r}
tribble(
  ~ Name, ~ Relationship, ~ Contact,
  "Ryan Gentzler", "Former Supervisor", "(918) 519-3487",
  "Nathan Pickard", "Data Collaborator", "(918) 732-9191",
  "Shiloh Kantz", "Former Supervisor", "(918) 406-5270"
) |>
  detailed_entries(Name, "", Relationship, Contact)
```
